# -*- coding: utf-8 -*-
"""nii_to_csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17AOl4CBn-9JI6jVe7rrQ3oApEk7eZKKr

!pip install nilearn
"""

#By Sara Camila Laura Manzaneda
!pip install nilearn

from google.colab import drive
drive.mount('/content/drive')

from nilearn import image
from nilearn import plotting
import numpy as np
import nibabel as nib
from google.colab import drive
import glob
drive.mount('/content/drive') # les pedirá una autorización
#!cp "/content/drive/My Drive/CIDIMEC-RESEARCH/DATSETS/ZIP_VIM-1" "VIM-1"
#!cd '/content/drive/My Drive/CIDIMEC-RESEARCH/DATSETS/ZIP_VIM-1'
#rsn=!cd '/content/drive/My Drive/CIDIMEC-RESEARCH/DATSETS/ZIP_VIM-1/Sub1_Ses1_Run1_Trn.nii.gz'

root_path = '/content/drive/My Drive/CIDIMEC-RESEARCH/DATSETS/fMRI on ImageNET (NUEVO)/derivatives/preproc-spm/output/sub-01/ses-anatomy/anat/sub-01_ses-anatomy_T1w_preproc.nii.gz'#cambiar el archivo  '/content/drive/My Drive/CIDIMEC-RESEARCH/DATSETS/ZIP_VIM-1/Sub1_Ses3_Run2_Trn.nii.gz'
array_img=image.load_img(root_path)
image_data = array_img.get_fdata()
a=np.array(image_data)
w=a.swapaxes(1, 2).reshape(a.shape[0]*a.shape[1],a.shape[2]*a.shape[3])
w.shape
np.savetxt("/content/drive/My Drive/CIDIMEC-RESEARCH/DATSETS/fMRI on ImageNet (CSV)/derivatives/preproc-spm/output/sub-01/ses-anatomy/anat/sub-01_ses-anatomy_T1w_preproc.csv", w, delimiter=";") #poner nombre del nii con .csv